import '../models/deal.dart';
import '../models/loyalty.dart';
import '../models/vendor.dart';
import '../models/voucher.dart';
import '../providers/deals_provider.dart';

/// Set to true to use mock data instead of API
const bool useMockData = false;

final _now = DateTime.now();

// ── DEALS ──────────────────────────────────────────────────────────────────

final List<Deal> mockDeals = [
  Deal(
    id: 'deal_1',
    vendorId: 'v1',
    vendorName: 'Mama Nkechi Kitchen',
    vendorIsOpen: true,
    vendorOpensAt: '07:00',
    vendorClosesAt: '21:00',
    title: 'Jollof Rice + Chicken Combo',
    description: 'Delicious home-style jollof rice with a big piece of chicken and plantain. A student favourite since 2019. Gets sold out by 2PM daily.',
    category: 'FOOD',
    imageUrl: null,
    originalPrice: 250000,
    studentPrice: 180000,
    savings: 70000,
    totalQuantity: 50,
    remainingQty: 8,
    maxPerUser: 2,
    startsAt: _now,
    expiresAt: _now.add(const Duration(days: 7)),
    isFeatured: true,
    featuredSection: 'Hot in Akoka',
    tags: ['bestseller', 'jollof', 'chicken'],
  ),
  Deal(
    id: 'deal_2',
    vendorId: 'v1',
    vendorName: 'Mama Nkechi Kitchen',
    vendorIsOpen: true,
    vendorOpensAt: '07:00',
    vendorClosesAt: '21:00',
    title: 'Shawarma Special',
    description: 'Loaded chicken shawarma with extra garlic sauce, cabbage, and fries on the side. The biggest shawarma on campus.',
    category: 'FOOD',
    imageUrl: null,
    originalPrice: 200000,
    studentPrice: 150000,
    savings: 50000,
    totalQuantity: 40,
    remainingQty: 5,
    maxPerUser: 3,
    startsAt: _now,
    expiresAt: _now.add(const Duration(days: 7)),
    isFeatured: true,
    featuredSection: 'Hot in Akoka',
    tags: ['shawarma', 'chicken'],
  ),
  Deal(
    id: 'deal_3',
    vendorId: 'v2',
    vendorName: 'ChillZone Cafe',
    vendorIsOpen: true,
    vendorOpensAt: '10:00',
    vendorClosesAt: '22:00',
    title: 'Iced Coffee + Pastry',
    description: 'Cold brew iced coffee paired with a freshly baked chocolate or vanilla pastry. Perfect for long library sessions.',
    category: 'DRINKS',
    imageUrl: null,
    originalPrice: 150000,
    studentPrice: 100000,
    savings: 50000,
    totalQuantity: 25,
    remainingQty: 3,
    maxPerUser: 1,
    startsAt: _now,
    expiresAt: _now.add(const Duration(days: 7)),
    isFeatured: true,
    featuredSection: 'Hot in Akoka',
    tags: ['coffee', 'pastry', 'cafe'],
  ),
  Deal(
    id: 'deal_4',
    vendorId: 'v2',
    vendorName: 'ChillZone Cafe',
    vendorIsOpen: true,
    vendorOpensAt: '10:00',
    vendorClosesAt: '22:00',
    title: 'Smoothie Bowl',
    description: 'Fresh fruit smoothie bowl with granola, honey drizzle, and seasonal toppings. High-protein, great for post-class energy.',
    category: 'DRINKS',
    imageUrl: null,
    originalPrice: 180000,
    studentPrice: 120000,
    savings: 60000,
    totalQuantity: 20,
    remainingQty: 20,
    maxPerUser: 2,
    startsAt: _now,
    expiresAt: _now.add(const Duration(days: 7)),
    isFeatured: false,
    tags: ['smoothie', 'healthy'],
  ),
  Deal(
    id: 'deal_5',
    vendorId: 'v1',
    vendorName: 'Mama Nkechi Kitchen',
    vendorIsOpen: true,
    vendorOpensAt: '07:00',
    vendorClosesAt: '21:00',
    title: 'Fried Rice + Turkey',
    description: 'Tasty party-style fried rice served with a full turkey piece, coleslaw, and chilled zobo drink.',
    category: 'FOOD',
    imageUrl: null,
    originalPrice: 300000,
    studentPrice: 220000,
    savings: 80000,
    totalQuantity: 30,
    remainingQty: 30,
    maxPerUser: 1,
    startsAt: _now,
    expiresAt: _now.add(const Duration(days: 7)),
    isFeatured: false,
    tags: ['fried-rice', 'turkey'],
  ),
  Deal(
    id: 'deal_6',
    vendorId: 'v2',
    vendorName: 'ChillZone Cafe',
    vendorIsOpen: true,
    vendorOpensAt: '10:00',
    vendorClosesAt: '22:00',
    title: 'Game Pass (2 Hours)',
    description: '2 hours of unlimited gaming at ChillZone. PS5, Xbox, pool table, or board games. Bring a friend — both can use one pass.',
    category: 'LIFESTYLE',
    imageUrl: null,
    originalPrice: 200000,
    studentPrice: 130000,
    savings: 70000,
    totalQuantity: 15,
    remainingQty: 15,
    maxPerUser: 1,
    startsAt: _now,
    expiresAt: _now.add(const Duration(days: 7)),
    isFeatured: false,
    tags: ['gaming', 'ps5'],
  ),
  Deal(
    id: 'deal_7',
    vendorId: 'v3',
    vendorName: 'TechHub Store',
    vendorIsOpen: true,
    vendorOpensAt: '09:00',
    vendorClosesAt: '20:00',
    title: 'MTN 1GB Data Bundle',
    description: 'MTN 1GB data valid for 30 days. Instant activation — no queues, no hassle. Works on all MTN SIMs.',
    category: 'SUBSCRIPTIONS',
    imageUrl: null,
    originalPrice: 50000,
    studentPrice: 35000,
    savings: 15000,
    totalQuantity: 100,
    remainingQty: 87,
    maxPerUser: 5,
    startsAt: _now,
    expiresAt: _now.add(const Duration(days: 30)),
    isFeatured: false,
    tags: ['data', 'mtn'],
  ),
  Deal(
    id: 'deal_8',
    vendorId: 'v4',
    vendorName: 'Campus Shuttle',
    vendorIsOpen: true,
    vendorOpensAt: '06:00',
    vendorClosesAt: '22:00',
    title: 'Weekly Shuttle Pass',
    description: 'Unlimited shuttle rides between UNILAG main gate and Yaba for 7 days. Air-conditioned. No more danfo stress.',
    category: 'TRANSPORT',
    imageUrl: null,
    originalPrice: 300000,
    studentPrice: 200000,
    savings: 100000,
    totalQuantity: 30,
    remainingQty: 7,
    maxPerUser: 1,
    startsAt: _now,
    expiresAt: _now.add(const Duration(days: 7)),
    isFeatured: false,
    tags: ['transport', 'shuttle'],
  ),
  Deal(
    id: 'deal_9',
    vendorId: 'v3',
    vendorName: 'TechHub Store',
    vendorIsOpen: true,
    vendorOpensAt: '09:00',
    vendorClosesAt: '20:00',
    title: 'Netflix 1-Month Sub',
    description: 'Full Netflix standard plan for 1 month. Stream on 2 screens simultaneously. HD quality.',
    category: 'SUBSCRIPTIONS',
    imageUrl: null,
    originalPrice: 420000,
    studentPrice: 320000,
    savings: 100000,
    totalQuantity: 50,
    remainingQty: 22,
    maxPerUser: 1,
    startsAt: _now,
    expiresAt: _now.add(const Duration(days: 30)),
    isFeatured: false,
    tags: ['netflix', 'streaming'],
  ),
  Deal(
    id: 'deal_10',
    vendorId: 'v5',
    vendorName: 'FreshCuts Barbershop',
    vendorIsOpen: true,
    vendorOpensAt: '09:00',
    vendorClosesAt: '19:00',
    title: 'Student Haircut + Beard',
    description: 'Fresh low cut or fade with beard line-up. Show your student ID and BuzzPay voucher. Walk in or pre-book.',
    category: 'LIFESTYLE',
    imageUrl: null,
    originalPrice: 150000,
    studentPrice: 100000,
    savings: 50000,
    totalQuantity: 20,
    remainingQty: 12,
    maxPerUser: 1,
    startsAt: _now,
    expiresAt: _now.add(const Duration(days: 7)),
    isFeatured: false,
    tags: ['haircut', 'grooming'],
  ),
];

// ── HAPPY HOUR (live right now) ─────────────────────────────────────────────

final List<Deal> mockHappyHour = [
  Deal(
    id: 'hh_1',
    vendorId: 'v1',
    vendorName: 'Mama Nkechi Kitchen',
    vendorIsOpen: true,
    vendorOpensAt: '07:00',
    vendorClosesAt: '21:00',
    title: 'Amala + Ewedu Combo',
    description: 'Mama Nkechi\'s famous amala with ewedu soup and assorted meat. Only available 12–2PM.',
    category: 'FOOD',
    imageUrl: null,
    originalPrice: 200000,
    studentPrice: 120000,
    savings: 80000,
    totalQuantity: 15,
    remainingQty: 6,
    maxPerUser: 1,
    startsAt: _now,
    expiresAt: _now.add(const Duration(minutes: 45)),
    isFeatured: false,
    featuredSection: 'Lunch Rush',
    tags: ['amala', 'soup'],
  ),
  Deal(
    id: 'hh_2',
    vendorId: 'v2',
    vendorName: 'ChillZone Cafe',
    vendorIsOpen: true,
    vendorOpensAt: '10:00',
    vendorClosesAt: '22:00',
    title: 'Milkshake + Cookie',
    description: 'Thick milkshake (vanilla, chocolate, or strawberry) with a warm chocolate chip cookie. Happy hour only.',
    category: 'DRINKS',
    imageUrl: null,
    originalPrice: 150000,
    studentPrice: 80000,
    savings: 70000,
    totalQuantity: 10,
    remainingQty: 4,
    maxPerUser: 1,
    startsAt: _now,
    expiresAt: _now.add(const Duration(minutes: 30)),
    isFeatured: false,
    featuredSection: 'Lunch Rush',
    tags: ['milkshake', 'dessert'],
  ),
  Deal(
    id: 'hh_3',
    vendorId: 'v1',
    vendorName: 'Mama Nkechi Kitchen',
    vendorIsOpen: true,
    vendorOpensAt: '07:00',
    vendorClosesAt: '21:00',
    title: 'Suya Platter',
    description: 'Fresh hot suya with sliced onions, tomatoes, and pepper. Night-time special 7–9PM.',
    category: 'FOOD',
    imageUrl: null,
    originalPrice: 180000,
    studentPrice: 100000,
    savings: 80000,
    totalQuantity: 20,
    remainingQty: 9,
    maxPerUser: 2,
    startsAt: _now,
    expiresAt: _now.add(const Duration(minutes: 55)),
    isFeatured: false,
    featuredSection: 'Lunch Rush',
    tags: ['suya', 'grilled'],
  ),
];

// ── UPCOMING / DROPPING SOON ────────────────────────────────────────────────

final List<Deal> mockUpcoming = [
  Deal(
    id: 'up_1',
    vendorId: 'v2',
    vendorName: 'ChillZone Cafe',
    vendorIsOpen: false,
    vendorOpensAt: '18:00',
    vendorClosesAt: '22:00',
    title: 'Evening Pizza Special',
    description: 'Two slices of pepperoni pizza + a drink. Drops at 6PM every evening.',
    category: 'FOOD',
    imageUrl: null,
    originalPrice: 280000,
    studentPrice: 180000,
    savings: 100000,
    totalQuantity: 25,
    remainingQty: 25,
    maxPerUser: 2,
    startsAt: _now.add(const Duration(hours: 3)),
    expiresAt: _now.add(const Duration(hours: 7)),
    isFeatured: false,
    dailyStart: '18:00',
    tags: ['pizza', 'evening'],
  ),
  Deal(
    id: 'up_2',
    vendorId: 'v1',
    vendorName: 'Mama Nkechi Kitchen',
    vendorIsOpen: false,
    vendorOpensAt: '19:00',
    vendorClosesAt: '21:00',
    title: 'Night Pepper Soup',
    description: 'Hot assorted pepper soup. Perfect for the cold library nights. Limited bowls.',
    category: 'FOOD',
    imageUrl: null,
    originalPrice: 220000,
    studentPrice: 150000,
    savings: 70000,
    totalQuantity: 20,
    remainingQty: 20,
    maxPerUser: 1,
    startsAt: _now.add(const Duration(hours: 5)),
    expiresAt: _now.add(const Duration(hours: 8)),
    isFeatured: false,
    dailyStart: '19:00',
    tags: ['pepper-soup', 'night'],
  ),
  // ── Amala Rush (grouped upcoming) ──
  Deal(
    id: 'up_3',
    vendorId: 'v1',
    vendorName: 'Mama Nkechi Kitchen',
    vendorIsOpen: false,
    vendorOpensAt: '12:00',
    vendorClosesAt: '14:00',
    title: 'Amala + Gbegiri Combo',
    description: 'Mama Nkechi\'s creamy gbegiri with amala and assorted meat. Lunch only.',
    category: 'FOOD',
    imageUrl: null,
    originalPrice: 220000,
    studentPrice: 140000,
    savings: 80000,
    totalQuantity: 20,
    remainingQty: 20,
    maxPerUser: 1,
    startsAt: _now.add(const Duration(hours: 2)),
    expiresAt: _now.add(const Duration(hours: 4)),
    isFeatured: false,
    featuredSection: 'Amala Rush',
    dailyStart: '12:00',
    tags: ['amala', 'gbegiri'],
  ),
  Deal(
    id: 'up_4',
    vendorId: 'v2',
    vendorName: 'ChillZone Cafe',
    vendorIsOpen: false,
    vendorOpensAt: '12:00',
    vendorClosesAt: '14:00',
    title: 'Amala + Ewedu Special',
    description: 'ChillZone\'s take on amala with ewedu and stew. Big portions.',
    category: 'FOOD',
    imageUrl: null,
    originalPrice: 200000,
    studentPrice: 130000,
    savings: 70000,
    totalQuantity: 15,
    remainingQty: 15,
    maxPerUser: 1,
    startsAt: _now.add(const Duration(hours: 2)),
    expiresAt: _now.add(const Duration(hours: 4)),
    isFeatured: false,
    featuredSection: 'Amala Rush',
    dailyStart: '12:00',
    tags: ['amala', 'ewedu'],
  ),
  Deal(
    id: 'up_5',
    vendorId: 'v5',
    vendorName: 'FreshCuts Barbershop',
    vendorIsOpen: false,
    vendorOpensAt: '12:00',
    vendorClosesAt: '14:00',
    title: 'Amala Platter Deluxe',
    description: 'Full amala platter with abula (gbegiri + ewedu mix) and goat meat.',
    category: 'FOOD',
    imageUrl: null,
    originalPrice: 300000,
    studentPrice: 180000,
    savings: 120000,
    totalQuantity: 10,
    remainingQty: 10,
    maxPerUser: 1,
    startsAt: _now.add(const Duration(hours: 2)),
    expiresAt: _now.add(const Duration(hours: 4)),
    isFeatured: false,
    featuredSection: 'Amala Rush',
    dailyStart: '12:00',
    tags: ['amala', 'abula'],
  ),
];

// ── FEATURED (subset of deals) ──────────────────────────────────────────────

final List<Deal> mockFeatured = mockDeals.where((d) => d.isFeatured).toList();

// ── TRENDING VENDORS ────────────────────────────────────────────────────────

final List<TrendingVendor> mockTrendingVendors = [
  TrendingVendor(id: 'v1', businessName: 'Mama Nkechi', logoUrl: null),
  TrendingVendor(id: 'v2', businessName: 'ChillZone', logoUrl: null),
  TrendingVendor(id: 'v3', businessName: 'TechHub', logoUrl: null),
  TrendingVendor(id: 'v4', businessName: 'Shuttle Co.', logoUrl: null),
  TrendingVendor(id: 'v5', businessName: 'FreshCuts', logoUrl: null),
];

// ── COLLECTIONS (tag-grouped) ────────────────────────────────────────────────

final List<DealCollection> mockCollections = [
  DealCollection(
    tag: 'bestseller',
    title: 'Best Sellers This Week',
    deals: mockDeals.where((d) => d.tags?.contains('bestseller') == true || d.remainingQty < 10).take(4).toList(),
  ),
  DealCollection(
    tag: 'data',
    title: 'Data & Streaming Deals',
    deals: mockDeals.where((d) => d.category == 'SUBSCRIPTIONS').toList(),
  ),
];

// ── VOUCHERS ────────────────────────────────────────────────────────────────

final List<Voucher> mockVouchers = [
  // Active — shows in home carousel + vouchers tab
  Voucher(
    id: 'voucher_1',
    code: 'BZ7742XP',
    qrData: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    status: 'ACTIVE',
    expiresAt: _now.add(const Duration(hours: 6)),
    createdAt: _now.subtract(const Duration(minutes: 30)),
    deal: VoucherDeal(
      title: 'Jollof Rice + Chicken Combo',
      imageUrl: null,
      vendorName: 'Mama Nkechi Kitchen',
      studentPrice: 180000,
    ),
  ),
  Voucher(
    id: 'voucher_2',
    code: 'BZ9921KM',
    qrData: 'f1e2d3c4-b5a6-7890-dcba-098765432100',
    status: 'ACTIVE',
    expiresAt: _now.add(const Duration(hours: 2)),
    createdAt: _now.subtract(const Duration(hours: 1)),
    deal: VoucherDeal(
      title: 'Shawarma Special',
      imageUrl: null,
      vendorName: 'Mama Nkechi Kitchen',
      studentPrice: 150000,
    ),
  ),
  Voucher(
    id: 'voucher_3',
    code: 'BZ5533QR',
    qrData: 'c3c3c3c3-d4d4-5555-aaaa-bbbbccccdddd',
    status: 'ACTIVE',
    expiresAt: _now.add(const Duration(hours: 12)),
    createdAt: _now.subtract(const Duration(hours: 2)),
    deal: VoucherDeal(
      title: 'Iced Coffee + Pastry',
      imageUrl: null,
      vendorName: 'ChillZone Cafe',
      studentPrice: 100000,
    ),
  ),
  // Redeemed — shows in history tab
  Voucher(
    id: 'voucher_4',
    code: 'BZ1122AB',
    qrData: 'eeee1111-2222-3333-4444-555566667777',
    status: 'REDEEMED',
    expiresAt: _now.subtract(const Duration(hours: 10)),
    redeemedAt: _now.subtract(const Duration(hours: 12)),
    createdAt: _now.subtract(const Duration(days: 1)),
    deal: VoucherDeal(
      title: 'Smoothie Bowl',
      imageUrl: null,
      vendorName: 'ChillZone Cafe',
      studentPrice: 120000,
    ),
  ),
  Voucher(
    id: 'voucher_5',
    code: 'BZ3366YY',
    qrData: 'dddd3333-4444-5555-6666-777788889999',
    status: 'REDEEMED',
    expiresAt: _now.subtract(const Duration(hours: 4)),
    redeemedAt: _now.subtract(const Duration(hours: 5)),
    createdAt: _now.subtract(const Duration(days: 2)),
    deal: VoucherDeal(
      title: 'Fried Rice + Turkey',
      imageUrl: null,
      vendorName: 'Mama Nkechi Kitchen',
      studentPrice: 220000,
    ),
  ),
  // Expired — shows in history tab
  Voucher(
    id: 'voucher_6',
    code: 'BZ8844ZZ',
    qrData: 'ffff8888-9999-aaaa-bbbb-ccccddddeeee',
    status: 'EXPIRED',
    expiresAt: _now.subtract(const Duration(days: 1)),
    createdAt: _now.subtract(const Duration(days: 2)),
    deal: VoucherDeal(
      title: 'Game Pass (2 Hours)',
      imageUrl: null,
      vendorName: 'ChillZone Cafe',
      studentPrice: 130000,
    ),
  ),
];

// ── VENDORS ──────────────────────────────────────────────────────────────────

Vendor _buildVendor(
  String id,
  String name,
  String address,
  String opensAt,
  String closesAt,
  String? coverUrl,
  double rating,
  int students,
  List<String> tags,
  bool isOpen,
) {
  return Vendor(
    id: id,
    businessName: name,
    businessAddress: address,
    coverUrl: coverUrl,
    isOpen: isOpen,
    opensAt: opensAt,
    closesAt: closesAt,
    rating: rating,
    totalStudents: students,
    buzzTags: tags,
    deals: [
      ...mockDeals.where((d) => d.vendorId == id),
      ...mockHappyHour.where((d) => d.vendorId == id),
    ],
  );
}

final Map<String, Vendor> mockVendorsMap = {
  'v1': _buildVendor(
    'v1', 'Mama Nkechi Kitchen',
    'Shop 5, UNILAG Main Gate, Akoka',
    '07:00', '21:00',
    null,
    4.7, 342,
    ['🔥 Student Favourite', '🍗 Large Portions', '⚡ Fast Prep'],
    true,
  ),
  'v2': _buildVendor(
    'v2', 'ChillZone Cafe',
    '12 University Road, Akoka, Lagos',
    '10:00', '22:00',
    null,
    4.4, 218,
    ['☕ Great Coffee', '🎮 Gaming Lounge', '📶 Free Wi-Fi'],
    true,
  ),
  'v3': _buildVendor(
    'v3', 'TechHub Store',
    'Block C, Student Union Building, UNILAG',
    '09:00', '20:00',
    null,
    4.2, 95,
    ['📱 Data Bundles', '💻 Accessories', '⚡ Fast Service'],
    true,
  ),
  'v4': _buildVendor(
    'v4', 'Campus Shuttle',
    'UNILAG Main Gate Bus Stop',
    '06:00', '22:00',
    null,
    4.0, 150,
    ['🚌 AC Buses', '🕐 Runs Every 30min'],
    true,
  ),
  'v5': _buildVendor(
    'v5', 'FreshCuts Barbershop',
    'Off Moremi Road, UNILAG, Akoka',
    '09:00', '19:00',
    null,
    4.6, 180,
    ['✂️ Clean Cuts', '⏱ No Long Wait', '💈 Beard Work'],
    true,
  ),
};

// ── LOYALTY CARDS ────────────────────────────────────────────────────────────

final List<LoyaltyCard> mockLoyaltyCards = [
  LoyaltyCard(
    id: 'lc1',
    vendorId: 'v1',
    vendorName: 'Mama Nkechi Kitchen',
    stamps: 3,
    target: 5,
    rewardsUsed: 0,
  ),
  LoyaltyCard(
    id: 'lc2',
    vendorId: 'v2',
    vendorName: 'ChillZone Cafe',
    stamps: 5,
    target: 5,
    rewardsUsed: 0,
  ),
];
