import '../models/deal.dart';
import '../models/loyalty.dart';
import '../models/vendor.dart';
import '../models/voucher.dart';

/// Set to true to use mock data instead of API
const bool useMockData = true;

final _now = DateTime.now();

final List<Deal> mockDeals = [
  Deal(
    id: 'deal_1',
    vendorId: 'v1',
    vendorName: 'Mama Nkechi Kitchen',
    vendorIsOpen: true,
    vendorOpensAt: '07:00',
    vendorClosesAt: '21:00',
    title: 'Jollof Rice + Chicken Combo',
    description: 'Delicious home-style jollof rice with a big piece of chicken and plantain.',
    category: 'FOOD',
    imageUrl: 'https://images.unsplash.com/photo-1639024471283-03518883512d?w=600',
    originalPrice: 250000,
    studentPrice: 180000,
    savings: 70000,
    totalQuantity: 50,
    remainingQty: 8,
    maxPerUser: 2,
    startsAt: _now,
    expiresAt: _now.add(const Duration(days: 7)),
    isFeatured: true,
  ),
  Deal(
    id: 'deal_2',
    vendorId: 'v1',
    vendorName: 'Mama Nkechi Kitchen',
    vendorIsOpen: true,
    vendorOpensAt: '07:00',
    vendorClosesAt: '21:00',
    title: 'Shawarma Special',
    description: 'Loaded chicken shawarma with extra sauce. Student size!',
    category: 'FOOD',
    imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600',
    originalPrice: 200000,
    studentPrice: 150000,
    savings: 50000,
    totalQuantity: 40,
    remainingQty: 5,
    maxPerUser: 3,
    startsAt: _now,
    expiresAt: _now.add(const Duration(days: 7)),
    isFeatured: true,
  ),
  Deal(
    id: 'deal_3',
    vendorId: 'v2',
    vendorName: 'ChillZone Cafe',
    vendorIsOpen: true,
    vendorOpensAt: '10:00',
    vendorClosesAt: '22:00',
    title: 'Iced Coffee + Pastry',
    description: 'Chill with an iced coffee and freshly baked pastry. Valid 2PM-5PM only.',
    category: 'DRINKS',
    imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600',
    originalPrice: 150000,
    studentPrice: 100000,
    savings: 50000,
    totalQuantity: 25,
    remainingQty: 3,
    maxPerUser: 1,
    startsAt: _now,
    expiresAt: _now.add(const Duration(days: 7)),
    isFeatured: true,
  ),
  Deal(
    id: 'deal_4',
    vendorId: 'v2',
    vendorName: 'ChillZone Cafe',
    vendorIsOpen: true,
    vendorOpensAt: '10:00',
    vendorClosesAt: '22:00',
    title: 'Smoothie Bowl',
    description: 'Fresh fruit smoothie bowl with granola and honey. Perfect study fuel!',
    category: 'DRINKS',
    imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=600',
    originalPrice: 180000,
    studentPrice: 120000,
    savings: 60000,
    totalQuantity: 20,
    remainingQty: 20,
    maxPerUser: 2,
    startsAt: _now,
    expiresAt: _now.add(const Duration(days: 7)),
    isFeatured: false,
  ),
  Deal(
    id: 'deal_5',
    vendorId: 'v1',
    vendorName: 'Mama Nkechi Kitchen',
    vendorIsOpen: true,
    vendorOpensAt: '07:00',
    vendorClosesAt: '21:00',
    title: 'Fried Rice + Turkey',
    description: 'Tasty fried rice served with turkey and coleslaw. Perfect for lunch!',
    category: 'FOOD',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600',
    originalPrice: 300000,
    studentPrice: 220000,
    savings: 80000,
    totalQuantity: 30,
    remainingQty: 30,
    maxPerUser: 1,
    startsAt: _now,
    expiresAt: _now.add(const Duration(days: 7)),
    isFeatured: false,
  ),
  Deal(
    id: 'deal_6',
    vendorId: 'v2',
    vendorName: 'ChillZone Cafe',
    vendorIsOpen: false,
    vendorOpensAt: '10:00',
    vendorClosesAt: '22:00',
    title: 'Game Pass (2 Hours)',
    description: 'Two hours of gaming at ChillZone. PS5, pool table, or board games.',
    category: 'LIFESTYLE',
    imageUrl: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=600',
    originalPrice: 200000,
    studentPrice: 130000,
    savings: 70000,
    totalQuantity: 15,
    remainingQty: 15,
    maxPerUser: 1,
    startsAt: _now,
    expiresAt: _now.add(const Duration(days: 7)),
    isFeatured: false,
  ),
  Deal(
    id: 'deal_7',
    vendorId: 'v1',
    vendorName: 'Mama Nkechi Kitchen',
    vendorIsOpen: true,
    vendorOpensAt: '07:00',
    vendorClosesAt: '21:00',
    title: '1GB Data Bundle',
    description: 'MTN 1GB data valid for 30 days.',
    category: 'SUBSCRIPTIONS',
    imageUrl: 'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=600',
    originalPrice: 50000,
    studentPrice: 35000,
    savings: 15000,
    totalQuantity: 100,
    remainingQty: 100,
    maxPerUser: 5,
    startsAt: _now,
    expiresAt: _now.add(const Duration(days: 7)),
    isFeatured: false,
  ),
  Deal(
    id: 'deal_8',
    vendorId: 'v2',
    vendorName: 'ChillZone Cafe',
    vendorIsOpen: true,
    vendorOpensAt: '10:00',
    vendorClosesAt: '22:00',
    title: 'Campus Shuttle Pass (Weekly)',
    description: 'Weekly unlimited shuttle rides between campus and Yaba.',
    category: 'TRANSPORT',
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600',
    originalPrice: 300000,
    studentPrice: 200000,
    savings: 100000,
    totalQuantity: 30,
    remainingQty: 7,
    maxPerUser: 1,
    startsAt: _now,
    expiresAt: _now.add(const Duration(days: 7)),
    isFeatured: false,
  ),
];

final List<Deal> mockHappyHour = [
  Deal(
    id: 'hh_1',
    vendorId: 'v1',
    vendorName: 'Mama Nkechi Kitchen',
    vendorIsOpen: true,
    vendorOpensAt: '07:00',
    vendorClosesAt: '21:00',
    title: 'Amala + Ewedu Combo',
    description: 'Mama Nkechi\'s famous amala with ewedu and assorted meat.',
    category: 'FOOD',
    imageUrl: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=600',
    originalPrice: 200000,
    studentPrice: 120000,
    savings: 80000,
    totalQuantity: 15,
    remainingQty: 6,
    maxPerUser: 1,
    startsAt: _now,
    expiresAt: _now.add(const Duration(minutes: 45)),
    isFeatured: false,
  ),
  Deal(
    id: 'hh_2',
    vendorId: 'v2',
    vendorName: 'ChillZone Cafe',
    vendorIsOpen: true,
    vendorOpensAt: '10:00',
    vendorClosesAt: '22:00',
    title: 'Milkshake + Cookie',
    description: 'Thick milkshake with a warm chocolate chip cookie.',
    category: 'DRINKS',
    imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600',
    originalPrice: 150000,
    studentPrice: 80000,
    savings: 70000,
    totalQuantity: 10,
    remainingQty: 4,
    maxPerUser: 1,
    startsAt: _now,
    expiresAt: _now.add(const Duration(minutes: 30)),
    isFeatured: false,
  ),
  Deal(
    id: 'hh_3',
    vendorId: 'v1',
    vendorName: 'Mama Nkechi Kitchen',
    vendorIsOpen: true,
    vendorOpensAt: '07:00',
    vendorClosesAt: '21:00',
    title: 'Suya Platter',
    description: 'Hot suya with onions and pepper.',
    category: 'FOOD',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600',
    originalPrice: 180000,
    studentPrice: 100000,
    savings: 80000,
    totalQuantity: 20,
    remainingQty: 9,
    maxPerUser: 2,
    startsAt: _now,
    expiresAt: _now.add(const Duration(minutes: 55)),
    isFeatured: false,
  ),
];

final List<Deal> mockFeatured = mockDeals.where((d) => d.isFeatured).toList();

final List<Voucher> mockVouchers = [
  Voucher(
    id: 'voucher_1',
    code: 'BZ7742XP',
    qrData: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    status: 'ACTIVE',
    expiresAt: _now.add(const Duration(hours: 6)),
    createdAt: _now,
    deal: VoucherDeal(
      title: 'Jollof Rice + Chicken Combo',
      imageUrl: 'https://images.unsplash.com/photo-1639024471283-03518883512d?w=600',
      vendorName: 'Mama Nkechi Kitchen',
      studentPrice: 180000,
    ),
  ),
  Voucher(
    id: 'voucher_2',
    code: 'BZ9921KM',
    qrData: 'f1e2d3c4-b5a6-7890-dcba-098765432100',
    status: 'ACTIVE',
    expiresAt: _now.add(const Duration(hours: 2)),
    createdAt: _now,
    deal: VoucherDeal(
      title: 'Shawarma Special',
      vendorName: 'Mama Nkechi Kitchen',
      studentPrice: 150000,
    ),
  ),
  Voucher(
    id: 'voucher_3',
    code: 'BZ5533QR',
    qrData: 'c3c3c3c3-d4d4-5555-aaaa-bbbbccccdddd',
    status: 'ACTIVE',
    expiresAt: _now.add(const Duration(hours: 6)),
    createdAt: _now,
    deal: VoucherDeal(
      title: 'Iced Coffee + Pastry',
      vendorName: 'ChillZone Cafe',
      studentPrice: 100000,
    ),
  ),
  Voucher(
    id: 'voucher_4',
    code: 'BZ1122AB',
    qrData: 'eeee1111-2222-3333-4444-555566667777',
    status: 'REDEEMED',
    expiresAt: _now.subtract(const Duration(hours: 12)),
    redeemedAt: _now.subtract(const Duration(hours: 12)),
    createdAt: _now.subtract(const Duration(days: 1)),
    deal: VoucherDeal(
      title: 'Smoothie Bowl',
      vendorName: 'ChillZone Cafe',
      studentPrice: 120000,
    ),
  ),
  Voucher(
    id: 'voucher_5',
    code: 'BZ8844ZZ',
    qrData: 'ffff8888-9999-aaaa-bbbb-ccccddddeeee',
    status: 'EXPIRED',
    expiresAt: _now.subtract(const Duration(days: 1)),
    createdAt: _now.subtract(const Duration(days: 2)),
    deal: VoucherDeal(
      title: 'Fried Rice + Turkey',
      vendorName: 'Mama Nkechi Kitchen',
      studentPrice: 220000,
    ),
  ),
];

// ── VENDORS ──

Vendor _buildVendor(String id, String name, String address, String opensAt,
    String closesAt, String coverUrl, double rating, int students,
    List<String> tags, bool isOpen) {
  return Vendor(
    id: id,
    businessName: name,
    businessAddress: address,
    coverUrl: coverUrl,
    isOpen: isOpen,
    opensAt: opensAt,
    closesAt: closesAt,
    rating: rating,
    totalStudents: students,
    buzzTags: tags,
    deals: mockDeals.where((d) => d.vendorId == id).toList()
      ..addAll(mockHappyHour.where((d) => d.vendorId == id)),
  );
}

final Map<String, Vendor> mockVendorsMap = {
  'v1': _buildVendor(
    'v1',
    'Mama Nkechi Kitchen',
    'Shop 5, UNILAG Main Gate, Akoka',
    '07:00',
    '21:00',
    'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
    4.7,
    342,
    ['🔥 Student Favorite', '🍗 Large Portions', '⚡ Fast Prep'],
    true,
  ),
  'v2': _buildVendor(
    'v2',
    'ChillZone Cafe',
    '12 University Road, Akoka, Lagos',
    '10:00',
    '22:00',
    'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
    4.4,
    218,
    ['☕ Great Coffee', '🎮 Gaming Lounge', '📶 Free Wi-Fi'],
    true,
  ),
};

// ── LOYALTY CARDS ──
final List<LoyaltyCard> mockLoyaltyCards = [
  LoyaltyCard(id: 'lc1', vendorId: 'v1', vendorName: 'Mama Nkechi Kitchen', stamps: 3, target: 5, rewardsUsed: 0),
  LoyaltyCard(id: 'lc2', vendorId: 'v2', vendorName: 'ChillZone Cafe', stamps: 5, target: 5, rewardsUsed: 0),
];
